name: PageSpeed Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow manual triggering
  workflow_dispatch:

concurrency:
  group: "pagespeed"
  cancel-in-progress: true

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"
          cache: true

      - name: Install dependencies
        run: bun install

      - name: Build site
        run: bun run build

      - name: Install Lighthouse and other tools
        run: bun add -g lighthouse serve wait-on

      - name: Serve static site
        run: serve -s dist -l 8080 &

      - name: Wait for server to start
        run: wait-on http://localhost:8080 -t 60000

      - name: Run Lighthouse audit
        run: |
          lighthouse http://localhost:8080 \
            --chrome-flags="--headless --no-sandbox" \
            --output=json \
            --output-path=./lhreport.json \
            --only-categories=performance,accessibility,best-practices,seo

      - name: Check performance score
        run: |
          PERFORMANCE=$(jq '.categories.performance.score' ./lhreport.json)
          ACCESSIBILITY=$(jq '.categories.accessibility.score' ./lhreport.json)
          BEST_PRACTICES=$(jq '.categories["best-practices"].score' ./lhreport.json)
          SEO=$(jq '.categories.seo.score' ./lhreport.json)

          echo "Performance score: $PERFORMANCE"
          echo "Accessibility score: $ACCESSIBILITY"
          echo "Best Practices score: $BEST_PRACTICES"
          echo "SEO score: $SEO"

          # Check if all scores are at least 0.95 (95%)
          if (( $(echo "$PERFORMANCE < 0.95" | bc -l) )) || \
             (( $(echo "$ACCESSIBILITY < 0.95" | bc -l) )) || \
             (( $(echo "$BEST_PRACTICES < 0.95" | bc -l) )) || \
             (( $(echo "$SEO < 0.95" | bc -l) )); then
            echo "❌ One or more scores are below 95%"
            exit 1
          else
            echo "✅ All scores are 95% or higher"
          fi

      - name: Upload Lighthouse report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: ./lhreport.json
